name: This Is my First Github Actions
on:
  push:
    branches: [ "master" ]
jobs:
  display-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print My name
        run: echo Hello Github Actions

  install-job:
    runs-on: ubuntu-latest
    steps:
       - name: Installing Apache
         run: sudo apt update; sudo apt install tree -y
